                             Part 1: Theoretical Queltionk

Q1.  What are the different data structures used in Tensorflow?. Give some examples.

TensorFlow, being a powerful framework for building and training machine learning models, relies on various data structures to handle data efficiently. Some of the key data structures used in TensorFlow include:

Tensors: Tensors are the fundamental data structures in TensorFlow. They are multi-dimensional arrays used to represent data of various types, including scalars, vectors, and matrices. Tensors are immutable, meaning their values cannot be changed once they are created.

Examples:- 


In [2]:
!pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.2/475.2 MB 3.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 12.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 75.1 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 64.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 72.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 11.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 23.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 74.5 MB/s eta 0:00:00ta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.0/442.0 kB 45.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 56.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 75.0 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 13.9 MB/

In [4]:

import tensorflow as tf

# Creating a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


2. Variables: Variables are mutable tensors that are used to hold and update the parameters of a model during training. They are typically used to store weights and biases.

Example:

In [5]:
variable = tf.Variable([[1, 2], [3, 4]])

print (variable)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>


3. Datasets: TensorFlow provides the tf.data.Dataset API to represent data input pipelines. Datasets allow efficient reading, preprocessing, and batching of data during training.

Example:

In [6]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5])

print(dataset)

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>


4. Sparse Tensors: Sparse tensors are used to efficiently represent tensors with a large number of zero values. They store only the non-zero values along with their indices.

Example:

Q2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an examples.

In TensorFlow, constants and variables are both used to store data, but they have different characteristics and purposes.

1. TensorFlow Constant:

Constants are tensors whose values cannot be changed once defined.

They are typically used to hold fixed data such as hyperparameters, configuration values, or input data that remains constant throughout the execution of a TensorFlow graph.

Constants are immutable, meaning their values remain fixed throughout the execution.

Example:

In [7]:
import tensorflow as tf

# Define a constant
const = tf.constant(3.0)

In [8]:
const

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

2. TensorFlow Variable:

Variables are tensors whose values can be changed during the execution of a TensorFlow graph.

They are typically used to hold model parameters that need to be optimized during training, such as weights and biases in neural networks.

Variables are mutable, meaning their values can be updated during the execution, making them suitable for optimization algorithms like gradient descent.

Example:

In [9]:
var = tf.Variable(3.0)

# Assign a new value to the variable
var.assign(4.0)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=4.0>

Q3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.


In TensorFlow, matrix addition, multiplication, and element-wise operations can be performed using tensors. Here's how each operation is performed:

1. Matrix Addition:
    
Matrix addition involves adding corresponding elements of two matrices of the same shape.

Example:

In [13]:
import tensorflow as tf

matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Perform matrix addition
result = tf.add(matrix1, matrix2)

print(result.numpy())  # Print the result

[[ 6  8]
 [10 12]]


In [ ]:
2. Matrix Multiplication:
    
Matrix multiplication involves multiplying rows of the first matrix with columns of the second matrix to produce a new matrix.

Example:

In [15]:
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Perform matrix addition
result = tf.matmul(matrix1, matrix2)

print(result.numpy())  # Print the result

[[19 22]
 [43 50]]


3. Element-wise Operations:

    Element-wise operations involve performing operations on corresponding elements of two tensors of the same shape.

Example:

In [16]:
import tensorflow as tf

tensor1 = tf.constant([[1, 2], [3, 4]])
tensor2 = tf.constant([[5, 6], [7, 8]])

# Perform element-wise addition
add_result = tf.add(tensor1, tensor2)

# Perform element-wise multiplication
multiply_result = tf.multiply(tensor1, tensor2)

print(add_result.numpy())      
print(multiply_result.numpy())

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


                            Part 2: Practical Implementation

Q4. Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the
values of matrix A.

You can create a 2x2 matrix filled with random values sampled from a normal distribution using TensorFlow's random_normal function. Here's how you can do it:

In [17]:
import tensorflow as tf

A = tf.random.normal(shape=(2, 2))

# Display the values of matrix A
print("Matrix A:")
print(A.numpy())

Matrix A:
[[-1.2988142   0.96485186]
 [-0.6210374  -0.30632767]]


Q5.  Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display
the values of matrix B.

In [19]:

B = tf.random.truncated_normal(shape=(4, 4), mean=0.0, stddev=1.0)

# Display the values of matrix B
print("Matrix B:")
print(B.numpy())

Matrix B:
[[ 0.63417006 -0.04487928 -0.06367643  0.405178  ]
 [-0.9992977  -0.01467684 -1.6671125  -0.6552118 ]
 [-1.3436536  -1.0356776  -0.48698983 -1.1566871 ]
 [-1.3074182  -0.46538964  0.37651992 -0.08832136]]


Q7. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a
mean of 2 and a standard deviation of 0.x, using TensorFlow's random.normal function. Display the values
of matrix C.

In [20]:
import tensorflow as tf

# Mean and standard deviation
mean = 2
stddev = 0.1  # Replace 0.x with the desired standard deviation

# Create a 2x2 matrix with random values from a normal distribution
C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)

print("Matrix C:")
print(C.numpy())

Matrix C:
[[2.0001817 1.9349862]
 [1.8883615 1.8262433]]


Q8. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [25]:
import tensorflow as tf

C = tf.constant([[1, 2], [3, 4]])
D = tf.constant([[5,6], [7,8]])

# Perform matrix multiplication between C and D
E = tf.matmul(C,D)

# Display the result matrix E
print("Matrix E (Result of C * D):")
print(E.numpy())


Matrix E (Result of C * D):
[[19 22]
 [43 50]]


                            Task 3 : Performing Additional Matrix Operations

Q9. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform functions

In [26]:
F = tf.random.uniform(shape=(2, 2))

# Display the values of matrix F
print("Matrix F:")
print(F.numpy())

Matrix F:
[[0.6474817  0.303285  ]
 [0.23031199 0.3978759 ]]


Q10.Calculate the transpose of matrix F and store the result in matrix G.

In [28]:
F = tf.random.uniform(shape=(2, 2))

G = tf.transpose(F)

print("Matrix G (Transpose of F):")
print(G.numpy())

Matrix G (Transpose of F):
[[0.69479513 0.29988825]
 [0.9710561  0.37201095]]


Q11. Calculate the element-wise exponential of matrix F and store the result in matrix H.

In [29]:
F = tf.random.uniform(shape=(2, 2))

H = tf.math.exp(F)

print("Matrix H (Element-wise Exponential of F):")
print(H.numpy())

Matrix H (Element-wise Exponential of F):
[[2.270745  1.8846856]
 [1.2123849 1.3232839]]


Q12. Create a matrix I by concatenating matrix F and matrix G horizontally.

In [31]:
F = tf.random.uniform(shape=(2, 2))
G = tf.transpose(F)

# Concatenate matrices F and G horizontally
I = tf.concat([F, G], axis=1)

print("Matrix I (Concatenation of F and G horizontally):")
print(I.numpy())

Matrix I (Concatenation of F and G horizontally):
[[0.01173019 0.5619614  0.01173019 0.36739957]
 [0.36739957 0.25989282 0.5619614  0.25989282]]


In [ ]:
Q13.Create a matrix J by concatenating matrix F and matrix H vertically.

In [32]:
F = tf.random.uniform(shape=(2, 2))
H = tf.transpose(J)

# Concatenate matrices F and G horizontally
I = tf.concat([F, H], axis=1)

print("Matrix I (Concatenation of F and G vertically):")
print(I.numpy())

NameError: name 'J' is not defined